version: '3'
services:
  flink-jobmanager:
    image: flink:1.14.4-scala_2.11-java8
    ports:
      - "8083:8081"
    command: jobmanager
    container_name: project_flink_jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        parallelism.default: 2
    networks:
      - pipeline_internal_system_network

  flink-taskmanager:
    image: flink:1.14.4-scala_2.11-java8
    depends_on:
      - flink-jobmanager
    command: taskmanager
    container_name: project_flink_taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2
    networks:
      - pipeline_internal_system_network

networks:
  pipeline_internal_system_network:
    driver: bridge